In [2]:
#Standard Imports
import torch
import numpy as np
np.set_printoptions(precision=3)

In [3]:
#Defining the arrays
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype=np.int32)

t_a = torch.tensor(a)
t_b = torch.from_numpy(b)

print(t_a, t_b, sep="\n")

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [4]:
#Defining a torch tensor with scalar value 1
tt_one = torch.ones([2, 3])
tt_one, tt_one.shape

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.Size([2, 3]))

In [5]:
#Creating a tensor filled with random values
tt_rand = torch.rand([2, 3])
tt_rand

tensor([[0.7911, 0.9835, 0.7266],
        [0.2937, 0.1953, 0.0394]])

In [6]:
#Casting an existing torch tensor to a specific type
t_a = t_a.to(torch.int64)
print(t_a.dtype)

torch.int64


In [7]:
# Performing some of the most common operations done on tensors

#Transposing a tensor
t = torch.rand([3, 5])
t_transp = torch.transpose(t, 0, 1)
print(t.shape, '-->', t_transp.shape)
print(t, '-->', t_transp)

torch.Size([3, 5]) --> torch.Size([5, 3])
tensor([[0.6733, 0.3155, 0.9995, 0.8220, 0.4047],
        [0.7892, 0.2716, 0.6656, 0.2805, 0.5206],
        [0.1423, 0.1473, 0.1546, 0.7426, 0.9827]]) --> tensor([[0.6733, 0.7892, 0.1423],
        [0.3155, 0.2716, 0.1473],
        [0.9995, 0.6656, 0.1546],
        [0.8220, 0.2805, 0.7426],
        [0.4047, 0.5206, 0.9827]])


In [8]:
#Reshaping a tensor from 1D to 2D array
t = torch.zeros(30)
t_res = t.reshape([5, 6])
print(t.shape , t_res.shape)
print(t, t_res, sep="\n")

torch.Size([30]) torch.Size([5, 6])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


In [9]:
#Removing the unecessary dimensions from a tensor
t = torch.zeros([1, 2, 1, 4, 1])
t_sqz = torch.squeeze(t, 2)
print(t.shape, t_sqz.shape)

torch.Size([1, 2, 1, 4, 1]) torch.Size([1, 2, 4, 1])


In [11]:
#Creating a Rank 3 tensor specifies the number of matricies as the first arg and the shape of each mat in the next 2 args
test = torch.rand([5, 3, 4])
test

tensor([[[0.0786, 0.5541, 0.7443, 0.1542],
         [0.4332, 0.9044, 0.9173, 0.7551],
         [0.0984, 0.8570, 0.7639, 0.1903]],

        [[0.8543, 0.5718, 0.2128, 0.8415],
         [0.3237, 0.7517, 0.7683, 0.0341],
         [0.0426, 0.3733, 0.7473, 0.8947]],

        [[0.5395, 0.0790, 0.5480, 0.2478],
         [0.5372, 0.0417, 0.6245, 0.4719],
         [0.3266, 0.0978, 0.0893, 0.1521]],

        [[0.1019, 0.1411, 0.5975, 0.7194],
         [0.9836, 0.6934, 0.3828, 0.9730],
         [0.4449, 0.9091, 0.6667, 0.4499]],

        [[0.5024, 0.1452, 0.2771, 0.9483],
         [0.0761, 0.2560, 0.8892, 0.2781],
         [0.1313, 0.9834, 0.2568, 0.6795]]])

APPLYING MATHEMATICAL OPERATIONS TO TENSORS

In [12]:
#Generating two tensors one with a unifomr dist and the other with
# a normal distribution

#Setting the manual seed 
torch.manual_seed(1)
t1 = 2*torch.rand([5, 2]) -1
t2 = torch.normal(mean=0, std=1, size=(5, 2))

#Applying the multiplication operator
t3 = torch.multiply(t1, t2)
print(t3)

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])


In [13]:
#Some operations cam also be performed on a specific axis of the tensor
#Matrix multiplication 
t_mat = torch.matmul(t1, torch.transpose(t2, 0, 1))
print(t_mat)

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])


In [20]:
#Applying mean, std and sum to a particualr axis of a tensor
print(t_mat.mean( axis=0), t_mat.sum(axis=0), sep="\n")

tensor([ 0.0251, -0.2112,  0.1692,  0.3881,  0.1030])
tensor([ 0.1256, -1.0559,  0.8459,  1.9403,  0.5148])
